
# CEDAR services base domain
CedarDomain=arp.orgx
CedarProxyApiKey=0000111122223333444455556666777788889999aaaabbbbccccddddeeeeffff

# Address of the solr updater service accessible to Dataverse. Defaults to docker installation address.
SolrUpdaterAddress=http://solr-updater:3000

# Comment out when ARP-like RO-Crate support is added
# Base URL to use for W3ID adressing.
# For prod: https://w3id.org/arp
# For dev: https://w3id.org/arp/dev
# For local dev: https://w3id.org/arp/localdev
# CedarW3idBase=https://w3id.org/arp/localdev


